In [1]:
import numpy as np
import math 
from sklearn.metrics import mean_squared_error
from sklearn.datasets import make_regression
import matplotlib.pylab as plt

In [2]:
def initialize_weights(n_features):
        "初始化系数，输入是feature的个数，输出是一个随机初始化好的参数矩阵,[-1/sqrt(N),1/sqrt(N)]"
        limit = 1/math.sqrt(n_features)
        print("limit:", limit)
        self.w = np.random.uniform(-limit,limit,(n_features,))

In [11]:
np.random.uniform(-1/3, 1/3, (3,))

array([-0.32951956,  0.11353005,  0.09244488])

In [10]:
math.sqrt(4)

2.0

In [12]:
a = np.random.uniform(-1, 1, (3,2))
a

array([[-0.46404503, -0.47790051],
       [-0.80431824,  0.20876755],
       [-0.00509597,  0.73972526]])

In [13]:
np.insert(a,0,1,axis=1)

array([[ 1.        , -0.46404503, -0.47790051],
       [ 1.        , -0.80431824,  0.20876755],
       [ 1.        , -0.00509597,  0.73972526]])

In [14]:
np.insert(a, 0, 1, axis=0)

array([[ 1.        ,  1.        ],
       [-0.46404503, -0.47790051],
       [-0.80431824,  0.20876755],
       [-0.00509597,  0.73972526]])