In [1]:
import numpy as np
import math 
from sklearn.metrics import mean_squared_error
from sklearn.datasets import make_regression
import matplotlib.pylab as plt

In [2]:
def initialize_weights(n_features):
        "初始化系数，输入是feature的个数，输出是一个随机初始化好的参数矩阵,[-1/sqrt(N),1/sqrt(N)]"
        limit = 1/math.sqrt(n_features)
        print("limit:", limit)
        self.w = np.random.uniform(-limit,limit,(n_features,))

In [3]:
# （3，2）表示3行2列
np.random.uniform(-1/3, 1/3, (3,))

array([-0.2832155 ,  0.294188  ,  0.22961645])

In [4]:
# 求平方根
math.sqrt(4)

2.0

In [5]:
a = np.random.uniform(-1, 1, (3,2))
a

array([[-0.25223752,  0.01506737],
       [ 0.02018246, -0.18357764],
       [ 0.63372258, -0.46014718]])

In [6]:
# 按照axis列的位置插入，第0列，插入1
np.insert(a,0,1,axis=1)

array([[ 1.        , -0.25223752,  0.01506737],
       [ 1.        ,  0.02018246, -0.18357764],
       [ 1.        ,  0.63372258, -0.46014718]])

In [7]:
# 按照行的位置插入，第0列，插入1
np.insert(a, 0, 1, axis=0)

array([[ 1.        ,  1.        ],
       [-0.25223752,  0.01506737],
       [ 0.02018246, -0.18357764],
       [ 0.63372258, -0.46014718]])

In [8]:
# 求均值
np.mean(np.array([[4,2],[3,4]]))

3.25

In [9]:
# 求L1范数
np.linalg.norm([1,2,3], ord=1)

6.0

In [10]:
# 求L2范数
np.linalg.norm([3, 4])  # sqrt(3**2+4**2)

5.0

In [11]:
# 求乘积之和，默认所有元素的乘积，axis=1时，各行列表乘积和
?np.prod

Signature:
np.prod(
    ['a', 'axis=None', 'dtype=None', 'out=None', 'keepdims=<no value>', 'initial=<no value>'],
)
Docstring:
Return the product of array elements over a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which a product is performed.  The default,
    axis=None, will calculate the product of all the elements in the
    input array. If axis is negative it counts from the last to the
    first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a product is performed on all of the
    axes specified in the tuple instead of a single axis or all the
    axes as before.
dtype : dtype, optional
    The type of the returned array, as well as of the accumulator in
    which the elements are multiplied.  The dtype of `a` is used by
    default unless `a` has an integer dtype of less precision than the
    default platform integer.  In that case, if `a` is signed then the
    pl

In [12]:
X = np.array([[1,2],[3,4]])

In [13]:
# 每列求平均
X.mean(0)

array([2., 3.])

In [21]:
# 每行求平均
np.array([[1,2],[4,5]]).mean(1)

array([1.5, 4.5])

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
y = np.array([1,0,1,333])

In [24]:
y.shape

(4,)

In [25]:
len(y.shape)

1

In [27]:
y = np.expand_dims(y, axis=1)

In [28]:
y

array([[  1],
       [  0],
       [  1],
       [333]])

In [31]:
X = np.array([[0,0,0,],[1,1,1],[2,2,2],[3,3,3]])

In [32]:
X

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [34]:
X = np.concatenate((X,y), axis=1)

In [35]:
X

array([[  0,   0,   0,   1],
       [  1,   1,   1,   0],
       [  2,   2,   2,   1],
       [  3,   3,   3, 333]])

In [37]:
np.expand_dims(X[:, 3], axis=1)

array([[  1],
       [  0],
       [  1],
       [333]])